project:
  type: website
  output-dir: ../docs

embed-resources: true

website:
  title: "PHES-EF"
  repo-subdir: qmd
  repo-url: "https://github.com/big-life-lab/PHES-EF"

  navbar:
    logo: assets/phes-ef-logo_colour.png
    background: primary
    search: true
    left:
      - text: Home
        href: index.qmd
      - href: about.qmd
      - href: methods.qmd
      - href: delphi.qmd
      - href: team.qmd
      - href: documents.qmd
      - href: contact.qmd
      - href: faq.qmd

    tools:
      - icon: github
        href: "https://github.com/big-life-lab/PHES-EF"

format:
  html:
    theme:
      - flatly # https://bootswatch.com/flatly/
      - assets/phes-odm.scss
      - assets/phes-ef.scss
    code-tools: false
    toc: true

bibliography: references.bib
csl: assets/vancouver.csl
