project:
  type: book
  output-dir: ../docs

book:
  title: "PBL Quarto Template"
  subtitle: ""
  date: last-modified
  date-format: iso
  license: CC 4.0 BY-SA
  repo-url: ""
  chapters:
    - index.qmd

format:
  html:
    toc: true
    theme:
      light: [cosmo, ./assets/phes-odm.scss]
    code-copy: true
    code-overflow: wrap
    lang: en-ca
  pdf:
    documentclass: scrbook
    toc: true
    number-sections: true
    colorlinks: true
