project:
  type: website
  output-dir: ../docs

website:
  title: "PHES-EF"
  repo-subdir: qmd
  repo-url: "https://github.com/big-life-lab/PHES-EF"
  
  navbar:
    logo: assets/phes-ef-logo_colour.png
    background: primary
    search: true
    left:
      - text: Home
        href: index.qmd
      - href: about.qmd
      
    tools:
      - icon: github
        href: "https://github.com/big-life-lab/PHES-EF"
      
format:
  html:
    theme: 
      - flatly
      - assets/phes-odm.scss
    toc: true
