
 project:
  type: website
  output-dir: docs

website:
  title: "PHES-EF"
  favicon: /Users/emmabrown/Downloads/phes-ef-logo_colour.png

  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - StudyTimeline.qmd
      - ContactUs.qmd
    logo: /Users/emmabrown/Downloads/phes-ef-logo_colour.png
    tools:
      - icon: twitter
        href: https://twitter.com
      - icon: github
      
format:
  html:
    theme: flatly
    font colour: black
    Link colour: blue
    css: styles.css
    toc: true

editor: visual


project:
  type: book
  output-dir: ../docs

book:
  title: "Public Health Environmental Surveillance - Evaluation Framework"
  subtitle: ""
  date: last-modified
  date-format: iso
  license: CC 4.0 BY-SA
  # url: 
  repo-url: "https://github.com/big-life-lab/PHES-EF"
  repo-actions: [edit, issue, source]
  repo-subdir: qmd
  downloads: [pdf, epub]
  sidebar:
    search: true
    logo: ./assets/icon.png
    
  chapters:
    - index.qmd
    - text: "---"
    - references.qmd
  # appendices:
    # - appendix.qmd

bibliography: references.bib
csl: assets/vancouver.csl

format:
  html:
    toc: true
    theme:
      light: [cosmo, ./assets/phes-odm.scss]
    code-copy: true
    code-overflow: wrap
    lang: en-ca
    use_issues_button: true
    use_repository_button: true
    
  pdf:
    documentclass: scrbook
    toc: true
    number-sections: true
    colorlinks: true
  
  epub: 
    # epub-cover-image: 
    fig-format: png
