project:
  type: website
  output-dir: ../docs
  
embed-resources: true

website:
  title: "PHES-EF"
  repo-subdir: qmd
  repo-url: "https://github.com/big-life-lab/PHES-EF"
  
  navbar:
    logo: assets/phes-ef-logo_colour.png
    background: primary
    search: true
    left:
      - text: Home
        href: index.qmd
      - text: Participate
        href: delphi.qmd
      - href: about.qmd
      - text: About the study
        href: study.qmd
      - href: publications.qmd
      - href: contact.qmd
      
    tools:
      - icon: github
        href: "https://github.com/big-life-lab/PHES-EF"
      
format:
  html:
    theme: 
      - flatly # https://bootswatch.com/flatly/
      - assets/phes-odm.scss
    code-tools: true
    toc: true

bibliography: references.bib
csl: assets/vancouver.csl
