project:
  type: website
  output-dir: docs

website:
  title: "PHES-EF"
  favicon: /Users/emmabrown/Downloads/phes-ef-logo_colour.png

website:
  # url: 
  repo-url: "https://github.com/big-life-lab/PHES-EF"
  sidebar:
    search: true
 
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - ContactUs.qmd
    tools:
      - icon: twitter
        href: https://twitter.com
      - icon: github
      
format:
  html:
    theme: flatly
    font colour: black
    Link colour: blue
    css: styles.css
    toc: true

editor: visual
