project:
  type: book
  output-dir: ../docs

book:
  title: "Public Health Environmental Surveillance - Evaluation Framework"
  subtitle: ""
  date: last-modified
  date-format: iso
  license: CC 4.0 BY-SA
  # url: 
  repo-url: "https://github.com/big-life-lab/PHES-EF"
  repo-actions: [edit, issue, source]
  repo-subdir: qmd
  downloads: [pdf, epub]
  sidebar:
    search: true
    logo: ./assets/icon.png
    
  chapters:
    - index.qmd
  # appendices:
    # - appendix.qmd

format:
  html:
    toc: true
    theme:
      light: [cosmo, ./assets/phes-odm.scss]
    code-copy: true
    code-overflow: wrap
    lang: en-ca
    use_issues_button: true
    use_repository_button: true
    
  pdf:
    documentclass: scrbook
    toc: true
    number-sections: true
    colorlinks: true
  
  epub: 
    # epub-cover-image: 
    fig-format: png
    

# bibliography: references.bib
# csl: ets
# citations-hover: true
# link-citations: true # pandoc setting
# latex-auto-mk: true
# link-external-icon: true
