project:
  type: website
  output-dir: docs

website:
  title: "PHES-EF"
  date: last-modified
  date-format: iso
  license: CC 4.0 BY-SA
  # url: 
  repo-url: "https://github.com/big-life-lab/PHES-EF"
   sidebar:
    search: true
    logo: ./assets/icon.png

  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    tools:
      - icon: twitter
        href: https://twitter.com
      - icon: github
      
format:
  html:
    theme: flatly
    font colour: black
    Link colour: blue
    css: styles.css
    toc: true

editor: visual
