---
title: "About"

bibliography: references.bib
---

This project will use a multidisciplinary and multinational consensus approach to develop an evaluation framework for public health environmental surveillance (Public Health Environmental Surveillance Evaluation Framework, *PHES-EF*) using wastewater surveillance as an example.

A structured system or schema to systematically assess a program [@fynn2020; \@calba2015]. An evaluation framework presents a clear list of items or elements such as constructs, concepts, that should appear in an evaluation; provides an organisation or structure for the list of items; defines how the list and organisation were developed; and, potentially, includes details about how to measure the evaluation items. Importantly, an evaluation framework facilitates informed decision-making by providing a comprehensive understanding of program effectiveness and areas for improvement.

## Approach

### Open science

The project will follow an open-science approach and make available the data for all project stages, including the search strategy, search findings, initial curation of evaluation measures, summary of executive group discussions, e-Delphi processes, and agreement procedures.

*PHES-EF* will be made available using an open license [(CC-BY-SA-4.0 license)](https://creativecommons.org/licenses/by-sa/4.0/). There will be a research data management plan to describe what data and information is available, and how to access tem. This will allow for the reuse of the data and the code, and will allow for the development of new tools and methods.

For more details, see the [license section](#licence) of this page.

### Equity, diversity, and inclusion (EDI)

"Equity is defined as the removal of systemic barriers and biases enabling all individuals to have equal opportunity to access and benefit from the program" [@schmalz2021]. To achieve this, members of the research team are committed to developing a strong understanding of the systemic barriers faced by individuals from underrepresented groups. "Diversity is defined as differences in race, colour, place of origin, religion, immigrant and newcomer status, ethnic origin, ability, sex, sexual orientation, gender identity, gender expression and age". Panellists will be asked to provide characteristic information (e.g., country of residence, gender, primary discipline) to assess and help ensure (through more targeted recruitment) a large diversity in perspectives. "Inclusion is defined as the practice of ensuring that all individuals are valued and respected for their contributions and are equally supported". To help ensure that all research team members are integrated and supported, we will have a code of conduct statement in the Executive Group Terms of Reference.

All study working group members will complete EDI-related Canadian Institutes for Health Research (CIHR) Training, and the First Nations principles of Ownership, Control, Access and Possession (OCAP©) training for the research [@ocap2023]. The executive group will receive an overview of EDI and OCAP and will be encouraged and supported to complete such training. Furthermore, staff trained in EDI and OCAP principles will review the framework from an EDI perspective to ensure appropriate language.

### Knowledge user and public involvement

To ensure accurate and transparent reporting of knowledge users and public involvement throughout the study, we will refer to the Guidance for Reporting Involvement of Patients and the Public (GRIPP2) checklist [@staniszewska2017]. We will document the methods used to engage knowledge users, report the impacts and outcomes of their engagement, and report on lessons learned from the experience.

## Declarations

### Funding

This project is funded by the Canadian Institutes for Health Research-funded network, CoVaRR-Net (Coronavirus Variants Rapid Response Network. FRN: 175622), and Health Canada (through the Safe Restart Agreement Contribution Program. Arrangement #: 2223-HQ-000098). The Canadian Institutes for Health Research and Health Canada have not been involved in the design or conduct or the study and the views expressed herein do not necessarily represent the views of either funding organization.

### Ethics approval and consent to participate

Ethical approval will be obtained from the Ottawa Health Science Network Research Ethics Board (OHSN-REB) before commencing the study Implied consent will be obtained from all panellists prior to participating in the e-Delphi survey. Information about the survey and consent practices will be provided on the first page of the survey. Panellists will be informed that by providing their demographic information and proceeding to the next page, they are providing their implied consent to participate in the study. Only anonymous panellist responses will be used for analyses.

OHSN-REB Number: 20230428-01H

If you have questions about ethical issues related to this study, you can talk to someone who is not involved in the study at the Ottawa Health Science Network Research Ethics Board, Chairperson at +1-613-798-5555 ext. 16719.

### Competing interests

All participants (i.e., study working group, executive group, and e-Delphi panellists) will be asked to declare any financial or personal relationships that may influence either the conduct or presentation of this research.

### Licence {#licence}

This website hosts a range of content, including references to journal articles, research papers, and other educational materials.

The majority of the content on this website is licensed under two Creative Commons licenses: CC-BY-4.0 (Creative Commons Attribution 4.0 International) and CC-BY-SA-4.0 (Creative Commons Attribution-ShareAlike 4.0 International).

Please see the [license page](https://github.com/Big-Life-Lab/PHES-EF/blob/main/LICENSE.md) for more information.

### Privacy

Anonymous aggregate data will be available on OSF, where the study protocol is registered. Individual responses to e-Delphi rounds will be anonymous at the source level by the platform used.

## References

::: {#refs}
:::
