---
title: "FAQ"

bibliography: references.bib
---

## Why is PHES-EF Needed?
Public health environmental surveillance has evolved, especially during the coronavirus disease (COVID-19) pandemic, with wastewater-based surveillance being a prominent example. As surveillance methods diversify and expand, there is a need to evaluate these systems to improve surveillance program accountability, transparency, and trust. 

It may even be argued that over the past few years only wastewater-based monitoring has increased rather than surveillance, as the data were not used to inform public health decision-making. This issue exemplifies the need for *PHES-EF*, as an evaluation framework for public health environmental surveillance systems is required to increase their reliability and credibility, to inform public health decision-making. In turn, this will also promote their value and sustainability as a public health tool.

There is also a need for such an evaluation framework as the recent and abrupt adoption of wastewater-based monitoring has resulted in poor standardization of analytic techniques, with ideal methods for reporting testing data still remaining unclear @manuel2021. Ultimately, *PHES-EF* aims to address this issue as well, as the framework is intended to be adopted by researchers to determine surveillance system performance and create analogous results for comparison within the field.

## What is a Delphi?
The Delphi method is an iterative multi-round approach that uses a series of sequential surveys, interspersed by controlled feedback, to elicit consensus among a group of individuals while maintaining anonymity @tricco2018 @nasa2021. An electronic Delphi (e-Delphi) method will be used to overcome geographic barriers and allow us to engage panellists internationally across various time zones. Delphi surveys relating to health sciences have typically been conducted over a period of 2-3 rounds @spranger2022 @shang2023 @junger2017. Therefore, a two-round e-Delphi survey paired with a subsequent consensus meeting will be conducted to balance feasibility with rigour. Each round will be active for approximately 4-6 weeks to allow panellists sufficient time to participate in the survey, while balancing study timeline constraints @niederberger2020. 

## Who is Eligible to Participate in the Study?
The eligibiligy criteria for e-Delphi survey panellists can be found [here.](delphi.qmd)

## References

::: {#refs}
:::
