---
title: "About"
format: html
bibliography: references.bib
---

## What is PHES-EF?
This project will use a multidisciplinary and multinational consensus approach to develop an evaluation framework for public health environmental surveillance (Public Health Environmental Surveillance Evaluation Framework, *PHES-EF*) using wastewater surveillance as an example. 

An evaluation framework provides structured guidance to facilitate a systematic approach to the evaluation of the program (14). While there is variation in the terminology used to describe frameworks (15), our approach will be as follows: present a clear list of items that should appear in an evaluation; provide an organisation or structure for the list of items; define how the list and organisation were developed; and, potentially, include details about how to measure the evaluation items. 

## Why is PHES-EF Needed?
Public health environmental surveillance has evolved, especially during the coronavirus disease (COVID-19) pandemic, with wastewater-based surveillance being a prominent example. As surveillance methods diversify and expand, there is a need to evaluate these systems to improve surveillance program accountability, transparency, and trust. 

Some may even argue that over the past few years there has only been increased wastewater-based monitoring rather than surveillance, as the data were not used to inform public health decision-making. This issue exemplifies the need for *PHES-EF* as an evaluation framework for public health environmental surveillance systems is required to increase their reliability and credibility, to inform public health decision-making. In turn, this will also promote their value and sustainability as a valuable public health tool.

There is also a need for such an evaluation framework as the recent and abrupt adoption of wastewater-based monitoring has resulted in poor standardization of analytic techniques, with ideal methods for reporting wastewater testing data also remaining unclear (1). Ultimately, *PHES-EF* aim to address this issue as well, as the framework is intended to be adopted by researchers to determine surveillance system performance and create analogous results for comparison within the field.


## Our Objectives
Specific objectives for the framework development process are as follows:

**1.** Engage a multidisciplinary executive group of international experts to inform the development of the evaluation framework

**2.** Review the literature to identify current guidance on surveillance evaluation items

**3.** Prioritize items for an evaluation framework for environmental surveillance using an international electronic-Delphi (e-Delphi) process

**4.** Conduct a consensus meeting that engages experts across disciplines to create an evaluation framework for public health environmental surveillance based    on feedback from the international e-Delphi process

**5.** Develop a comprehensive dissemination plan for the evaluation framework

## Our Approach
### Open Science

The project will follow an open-science approach and make available the data for all project stages, including the search strategy, search findings, initial curation of evaluation measures, summary of executive group discussions, e-Delphi processes, and agreement procedures.

*PHES-EF* will be made available using an open license [(CC-BY-SA-4.0 license)](https://creativecommons.org/licenses/by-sa/4.0/).

Anonymous aggregate data will be available on OSF, where the study protocol is registered. Individual responses to e-Delphi rounds will be anonymous at the source level by the platform used.

### Equity, Diversity, and Inclusion (EDI)

"Equity is defined as the removal of systemic barriers and biases enabling all individuals to have equal opportunity to access and benefit from the program"[@schmalz2021]. To achieve this, members of the research team are committed to developing a strong understanding of the systemic barriers faced by individuals from underrepresented groups. "Diversity is defined as differences in race, colour, place of origin, religion, immigrant and newcomer status, ethnic origin, ability, sex, sexual orientation, gender identity, gender expression and age". Panellists will be asked to provide characteristic information (e.g., country of residence, gender, primary discipline) to assess and help ensure (through more targeted recruitment) a large diversity in perspectives. "Inclusion is defined as the practice of ensuring that all individuals are valued and respected for their contributions and are equally supported". To help ensure that all research team members are integrated and supported, we will have a code of conduct statement in the Executive Group Terms of Reference.

All study working group members will complete EDI-related Canadian Institutes for Health Research (CIHR) Training, and the First Nations principles of Ownership, Control, Access and Possession (OCAP©) training for the research [@ocap2023]. The executive group will receive an overview of EDI and OCAP and will be encouraged and supported to complete such training. Furthermore, staff trained in EDI and OCAP principles will review the framework from an EDI perspective to ensure appropriate language.

### Knowledge User and Public Involvement

To ensure accurate and transparent reporting of knowledge users and public involvement throughout the study, we will refer to the Guidance for Reporting Involvement of Patients and the Public (GRIPP2) checklist [@staniszewska2017]. We will document the methods used to engage knowledge users, report the impacts and outcomes of their engagement, and report on lessons learned from the experience.

## Declarations
### Funding

This project is funded by the Canadian Institutes for Health Research-funded network, CoVaRR-Net (Coronavirus Variants Rapid Response Network. FRN: 175622), and Health Canada (through the Safe Restart Agreement Contribution Program. Arrangement #: 2223-HQ-000098). The Canadian Institutes for Health Research and Health Canada have not been involved in the design or conduct or the study and the views expressed herein do not necessarily represent the views of either funding organization.

### Ethics Approval and Consent to Participate

Ethical approval will be obtained from the Ottawa Health Science Network Research Ethics Board (OHSN-REB) before commencing the study Implied consent will be obtained from all panellists prior to participating in the e-Delphi survey. Information about the survey and consent practices will be provided on the first page of the survey. Panellists will be informed that by providing their demographic information and proceeding to the next page, they are providing their implied consent to participate in the study. Only anonymous panellist responses will be used for analyses.

OHSN-REB Number: 20230428-01H

If you have questions about ethical issues related to this study, you can talk to someone who is not involved in the study at the Ottawa Health Science Network Research Ethics Board, Chairperson at 1-613-798-5555 extension 16719.

### Competing Interests

All participants (i.e., study working group, executive group, and e-Delphi panellists) will be asked to declare any financial or personal relationships that may influence either the conduct or presentation of this research.

## References

::: {#refs}
:::
