---
title: "Contact Us"
---

::: justify-text
If you have any questions, comments, or are interested in participating in the study, please feel free to contact us at our study email address ([phes-ef\@ohri.ca](mailto:phes-ef@ohri.ca){.email}).

### Principal Investigator: Dr. Douglas Manuel 
Email: [dmanuel\@ohri.ca](mailto:dmanuel@ohri.ca){.email} | Tel: +1 613-798-5555 ext. 19108

Senior Scientist, Ottawa Hospital Research Institute<br>
Tier 1 Clinical Research Chair in Precision Medicine for Chronic Disease Prevention, Faculty of Medicine, University of Ottawa<br>
Distinguished University Professor, Department of Family Medicine, University of Ottawa<br>
Distinguished University Professor, School of Epidemiology, Public Health and Preventive Medicine, University of Ottawa<br>
Senior Investigator, Bruyère Research Institute<br>
Senior Core Scientist, ICES, Ontario<br>
Senior Medical Advisor, Statistics Canada, Ottawa<br>
Scientist, C.T. Lamont Primary Health Care Research Centre and Bruyère Research Institute
:::
