name: Publish docs to GitHub pages
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Build docs
        uses: ./.github/actions/build-docs-composite-action

      # New step to copy CNAME into the ./docs directory
      - name: Copy CNAME to docs
        run: cp CNAME ./docs/CNAME

      - name: Publish docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
